---
title: "final_data"
author: "Shai-Li Ron"
date: "3/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(dplyr)
library(janitor)
library(primer.data)


```

```{r}
# Moving the data from the cvs
covid_vac <- read_csv(file = "raw_data/vaccinated_city_table_ver_0022.csv", col_types = cols(
  .default = col_character(),
  CityCode = col_double(),
  Date = col_date(format = "")
)) 

```


```{r}
x <- covid_vac %>% 
clean_names 

# filter((first_dose_0_19 == "<15"),(first_dose_20_29 == "<15"), (first_dose_30_39 == "<15"), (first_dose_40_49 == "<15"), (first_dose_40_49 == "<15"), (first_dose_40_49 == "<15"), (first_dose_40_49 == "<15"), (first_dose_40_49 == "<15")



#mutate(first_dose_0_19 == "<15", 15)

#city name
#total first vaccine and total second vaccine

```

```{r}
clean_15 <- covid_vac %>% 
  clean_names() %>% 
  mutate(first_dose_0_19 = ifelse(first_dose_0_19 =="<15", 15, first_dose_0_19)) %>% 
  mutate(first_dose_20_29 = ifelse(first_dose_20_29 =="<15", 15, first_dose_20_29)) %>% 
  mutate(first_dose_30_39 = ifelse(first_dose_30_39 =="<15", 15, first_dose_30_39)) %>% 
  mutate(first_dose_40_49 = ifelse(first_dose_40_49 =="<15", 15, first_dose_40_49)) %>% 
   mutate(first_dose_50_59 = ifelse(first_dose_50_59 =="<15", 15, first_dose_50_59)) %>% 
 mutate( first_dose_60_69 = ifelse(first_dose_60_69 =="<15", 15,  first_dose_60_69)) %>% 
  mutate(first_dose_70_79 = ifelse(first_dose_70_79 =="<15", 15, first_dose_70_79)) %>% 
  mutate(first_dose_80_89 = ifelse(first_dose_80_89 =="<15", 15, first_dose_80_89)) %>% 
  mutate(first_dose_90 = ifelse(first_dose_90 =="<15", 15, first_dose_90))
   # select(date, starts_with("first_dose")) %>% 
  
  mutate(first_dose_90 = as.numeric(first_dose_90))

  # mutate(total = sum(first_dose_90))

# still trying to figure out how to do a total of them by each date, seems a little complicated. 

```

```{r}
clean_15
```


```{r}
clean_num <- clean_15 %>% 
mutate(first_dose_0_19 = as.numeric(first_dose_0_19)) %>% 
  mutate(first_dose_20_29 = as.numeric(first_dose_20_29)) %>% 
  mutate(first_dose_30_39 = as.numeric(first_dose_30_39)) %>% 
  mutate(first_dose_40_49 = as.numeric(first_dose_40_49)) %>% 
  mutate(first_dose_50_59 = as.numeric(first_dose_50_59)) %>% 
  mutate(first_dose_60_69 = as.numeric(first_dose_60_69)) %>% 
  mutate(first_dose_70_79 = as.numeric(first_dose_70_79)) %>% 
  mutate(first_dose_80_89 = as.numeric(first_dose_80_89)) %>% 
  mutate(first_dose_90 = as.numeric(first_dose_90)) 
  
```

```{r}
test_plot <- clean_num %>% 
  ggplot(aes(x = date,
             y = first_dose_0_19,
             color = city_code)) +
  geom_point() +
  labs(x = "Date",
       y = "Number of 0-19 Year-Olds First-Dose Vaccinated",
     title =  "Total Number of 0-19 Year-Olds Vaccinated Over Time",
       subtitle = "As time went by more 0-19 year olds got vaccinated",
       caption = "Source: Israeli National Health Service") +
  theme_gray()

  
  
  ggsave("test_plot.png", test_plot)
```


```{r}
total_ages <- clean_num %>% 
  mutate("0-19" = sum(first_dose_0_19)) %>% 
  mutate("20-29" = sum(first_dose_20_29)) %>% 
  mutate("30-39" = sum(first_dose_30_39)) %>% 
  mutate("40-49" = sum(first_dose_40_49)) %>% 
  mutate("50-59" = sum(first_dose_50_59)) %>% 
  mutate("60-69" = sum(first_dose_60_69)) %>% 
  mutate("70-79" = sum(first_dose_70_79)) %>% 
  mutate("80-89" = sum(first_dose_80_89)) %>% 
  mutate("90" = sum(first_dose_90)) %>% 
  pivot_longer(cols = "0-19" : "90",
               names_to = "age",
               values_to = "total") %>% 
  select(age, total)  

```


```{r}
p_total_ages <- total_ages %>% 
  mutate(total = total/1000000) %>% 
  ggplot(aes(x = age, 
             y = total)) +
  geom_point() +
  labs(x = "Age Group",
       y = "Total Vaccinated First Dose (millions)",
       title =  "Total Number of Vaccinated in Each Age Group",
       subtitle = "Ages 60-69 have the most vaccinated",
       caption = "Source: Israeli National Health Service") +
  theme_bw() 
ggsave("total_ages.png", p_total_ages)
 
```




```{r}
# covid_vac %>% 
# clean_names %>% 
# select(city_name, city_code, first_dose_80_89, second_dose_80_89) %>% 
#   filter(!(first_dose_80_89 == "<15")) %>% 
#   filter(!(second_dose_80_89 == "<15")) %>% 
#   group_by(city_code) %>% 
#   summarize(total_first_80s = count(first_dose_80_89), .groups = "drop")
```

```{r}
pic_tryout <- ggplot(trains, 
       aes(x = income)) +
  geom_density() +
  labs(title = "Income Among Boston Commuter",
       subtitle = "Why are there so few people with `middle' incomes?",
       x = "Income",
       y = NULL,
       caption = "Data source: Enos (2014)")


ggsave("pic.png", pic_tryout)

```


```{r}
column_names <- covid_vac %>% 
  clean_names %>% 
  select(starts_with("first_dose"), starts_with("second_dose")) %>% 
  colnames() %>% 
  as.vector()


```

